### ISSUE TITLE
mzML root not in index

### ISSUE THREAD

**Issue by lutzfischer** [PRIDE-Utilities/jmzml#20]
I was trying to read a mzML file generated with proteowizard 3.0.7414 msconvert

I am using jmzml-1.7.4 and xxindex-0.18

basically copying the code from 

**"A tutorial for software development in quantitative proteomics using PSI standard formats"**

when I try to read the the mzML file I get following error:
```
java.lang.IllegalStateException: Index does not contain mzML root!
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:100)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at rappsilber.ms.dataAccess.msm.MzMLIterator.inputFromFile(MzMLIterator.java:118)
	at rappsilber.ms.dataAccess.msm.MzMLIterator.<init>(MzMLIterator.java:108)
	at rappsilber.ms.dataAccess.msm.MzMLIterator.<init>(MzMLIterator.java:90)
...
```

the code throwing this is 
```
protected void inputFromFile(File msmfile) throws FileNotFoundException, ParseException, IOException {
        m_inputFile = msmfile;
        m_inputPath = msmfile.getAbsolutePath();
        m_source = msmfile.getName();

        unmarshaller = new MzMLUnmarshaller(msmfile);
        //Unmarshall mzML file
        spectrumIterator = unmarshaller.unmarshalCollectionFromXpath("/run/spectrumList/spectrum", uk.ac.ebi.jmzml.model.mzml.Spectrum.class);
        
        m_next.addAll(readScan()); // read first scan
        
    }
```

It failes on `unmarshaller = new MzMLUnmarshaller(msmfile);`

**Comment by ypriverol** [comment]
@lutzfischer can you provide me the file. to do the test!!!

**Comment by ypriverol** [comment]
I will close this issue because we don't have any evidences or file about the wrong behaviour. @lutzfischer feel free to open the issue again.
